# Generated by Django 4.1.1 on 2022-09-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pov', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='jensen/pov/static/pov/img/default.png', upload_to=None),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True),
        ),
    ]
