# Generated by Django 4.1.1 on 2022-09-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pov', '0002_album_cover_alter_album_album_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
